laboratorio/urls.py
from django.conf.urls import url
from laboratorio.views import ProjectTraza, UsuariosProyecto, ProtocolosExperimentosProyecto, ExperimentosProyecto
from .views import ProtocoloList, ProyectosLista, ExperimentoLista, ProtocolosExperimentoLista, ProjectProgressList, UsuariosLista
from . import views


urlpatterns = [
    url(r'^protocolofiltro/$', ProtocoloList.as_view(),name='ProtocoloFiltro'),
    url(r'^$', views.index, name='index'),
    url(r'^Proyecto/agregarProyecto/$', views.agregar_proyecto, name='agregarProyecto'),
    url(r'^Proyecto/editarProyecto/(?P<id>\d+)/$', views.editar_proyecto, name='editarProyecto'),
    url(r'^Experimento/agregarExperimento/(?P<idProy>\d+)/$', views.agregar_experimento, name='agregarExperimento'),
    url(r'^Experimento/editarExperimento/(?P<idExp>\d+)/$', views.editar_experimento, name='editarExperimento'),
    url(r'^Proyecto/listarProyectos/$', views.listar_proyectos, name='listarProyectos'),
    url(r'^Proyecto/filtrarProyectos/$', ProyectosLista.as_view(), name='filtrarProyectos'),
    url(r'^Experimento/listarExperimentos/$', views.listar_experimentos, name='listarExperimentos'),
    url(r'^Experimento/filtrarExperimentos/$', ExperimentoLista.as_view(), name='filtrarExperimentos'),
    url(r'^Experimento/detallarExperimento/(?P<idExp>\d+)/$', views.detallar_experimento, name='detallarExperimento'),
    url(r'^Experimento/iniciarExperimento/(?P<id>\d+)/$', views.start_experiment, name='startExperiment'),

    url(r'^patrocinadores/$', views.patrocinadores, name='patrocinadores'),
    url(r'^patrocinadores/(?P<id>\d+)/$', views.patrocinadores_id, name='patrocinadorId'),
    url(r'^Proyecto/proyectos/$', views.proyectos, name='proyectos'),
    url(r'^Proyecto/proyectos/(?P<id>\d+)/$', views.proyectos_id, name='proyectoId'),

    url(r'^responsables/$', views.responsables, name='responsables'),
    url(r'^responsables/(?P<id>\d+)/$', views.responsables_id, name='responsableId'),
    url(r'^Experimento/experimentos/$', views.experimentos, name='experimentos'),

    url(r'^Proyecto/proyectos/(?P<id>\d+)/experimentos/$', views.proyectos_id_experimentos, name='proyectoListExperimentos'),
    url(r'^Proyecto/proyectos/(?P<id>\d+)/experimentos/$', views.listar_experimentos, name='proyectoIdExperimentos'),
    url(r'^Experimento/experimentos/(?P<idProy>\d+)/experimentos/$', views.listar_experimentos, name='listaExperimentos'),

    url(r'^Experimento/experimentos/(?P<id>\d+)/$', views.experimentos_id, name='experimentoId'),
    url(r'^protocolos/$', views.protocolos, name='protocolos'),
    url(r'^Protocolo/listarProtocolos/$', views.listar_protocolos, name='listarProtocolos'),
    url(r'^protocolos/(?P<id>\d+)/$', views.protocolos_id, name='protocoloId'),
    url(r'^protocolos/editar/(?P<id>\d+)/$', views.edit_protocol, name='editProtocol'),
    url(r'^protocolosExperimento/$', views.protocolosExperimento, name='protocolosExperimento'),
    url(r'^protocolosExperimento/(?P<id>\d+)/$', views.protocolosExperimento_id, name='protocolosExperimentoId'),
    url(r'^Protocolo/detallarProtocolo/(?P<id>\d+)/$', views.detallar_protocolo, name='detallarProtocolo'),
    url(r'^pasos/$', views.pasos, name='pasos'),
    url(r'^pasos/(?P<id>\d+)/$', views.pasos_id, name='pasoId'),
    url(r'^elementos/$', views.elementos, name='elementos'),
    url(r'^elementos/(?P<id>\d+)/$', views.elementos_id, name='elementoId'),
    url(r'^protocolosExperimento/filtrarProtocolosExperimento/$', ProtocolosExperimentoLista.as_view(), name='filtrarProtocolosExperimentos'),

    url(r'^patrocinadores/(?P<id>\d+)/proyectos/$', views.patrocinadores_id_proyectos, name='patrocinadoresIdProyectos'),
    url(r'^Proyecto/proyectos/(?P<id>\d+)/experimentos/$', views.proyectos_id_experimentos, name='proyectosIdExperimentos'),
    url(r'^responsables/(?P<id>\d+)/experimentos/$', views.responsables_id_experimentos, name='responsablesIdExperimentos'),
    url(r'^Experimento/experimentos/(?P<id>\d+)/protocolos/$', views.experimentos_id_protocolos, name='experimentosIdProtocolos'),
    url(r'^protocolos/(?P<id>\d+)/experimentos/$', views.protocolos_id_experimentos, name='protocolosIdExperimentos'),
    url(r'^protocolos/(?P<id>\d+)/pasos/$', views.protocolos_id_pasos, name='protocolosIdPasos'),
    url(r'^pasos/(?P<id>\d+)/elementos/$', views.pasos_id_elementos, name='pasosIdElementos'),

    url(r'^protocolos/(?P<id>\d+)/nuevaVersion/$', views.protocolos_id_nueva_version, name='protocoloIdNuevaVersion'),
    url(r'^listaEstadosProyecto/$', views.lista_estados_proyecto, name='listaEstadosProyecto'),
    url(r'^listaEstadosExperimento/$', views.lista_estados_experimento, name='listaEstadosExperimento'),
    url(r'^listaNombreProyectos/$', views.lista_nombre_proyecto, name='listaNombreProyectos'),

    url(r'^listaResultadosExperimento/$', views.lista_resultados_experimento, name='listaResultadosExperimento'),
    url(r'^listaCategoriasProtocolo/$', views.lista_categorias_protocolo, name='listaCategoriasProtocolo'),
    url(r'^listaUnidadesElemento/$', views.lista_unidades_elemento, name='listaUnidadesElemento'),
    url(r'^Experimento/agregarExperimentoProtocolo/(?P<id>\d+)/$', views.agregar_expeprotocolo, name='agregarExperimentoProtocolo'),

    # Usuarios
    # URL paginas usuarios
    url(r'^agregarUsuario/$', views.agregar_usuario, name='agregarUsuario'),
    url(r'^login/$', views.inicio_sesion, name='login'),
    url(r'^usuarios/usuariosProyecto/(?P<id>\d+)/$', views.listar_usuariosProyecto, name='usuariosProyecto'),
    url(r'^usuarios/ListUserProject/', UsuariosLista.as_view(), name='listaUsuariosProy'),

    # URL servicios REST
    url(r'^usuarios/$', views.usuarios, name='usuarios'),
    url(r'^usuarios/(?P<id>\d+)/$', views.usuarios_id, name='usuarioId'),
    url(r'^iniciarSesion/$', views.iniciar_sesion, name='iniciarSesion'),
    url(r'^cerrarSesion/$', views.cerrar_sesion, name='cerrarSesion'),
    url(r'^estaLogueado/$', views.esta_logueado, name='estaLogueado'),

    #Project Progress
    url(r'^Proyecto/Avances/(?P<id>\d+)/$', views.list_progress, name='avance'),
    url(r'^Proyecto/AgregarAvance/(?P<id>\d+)/$', views.add_progress, name='agregarAvance'),
    url(r'^Proyecto/GuardarAvance/$', views.save_progress, name='guardarAvance'),
    url(r'^Proyecto/AvancesReportados/', ProjectProgressList.as_view(), name='avancesReportados'),

    #reports
    url(r'^Reportes/AvanceProyectos/', views.progress, name='reporteAvance'),
    url(r'^Reportes/trazabilidad/', views.trazabilidad, name='reporteTraza'),

    #Protocolos
    url(r'^agregarProtocolo/$', views.agregar_protocolo, name='agregarProtocolo'),

    #Trazabilidad
    url(r'^Proyecto/dataTraza/', UsuariosProyecto.as_view(), name='ProjectTraza'),
    url(r'^Proyecto/dataProto/', ProtocolosExperimentosProyecto.as_view(), name='ProjectProto'),
    url(r'^Proyecto/dataProto/', ExperimentosProyecto.as_view(), name='ProjectExpe'),

    #Deshabilitar protocolo
    url(r'^protocolos/(?P<id>\d+)/deshabilitar/$', views.protocolos_deshabilitar, name='protocoloIdDesahabilitar'),

]

proyLaboratorio/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^laboratorio/', include('laboratorio.urls', namespace='laboratorio'))
]

laboratorio/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from rest_framework.exceptions import ValidationError, NotFound
from models import Patrocinador, Proyecto
from datetime import datetime

# Create your views here.
def index(request):
    context = {'mensaje': 'Hola Mundo'}
    return render(request, 'laboratorio/index.html', context)
    #return HttpResponse("Hello, world. You're at the polls index.")

#Atiende las peticiones de los Patrocinadores
@csrf_exempt
def patrocinadores(request):

    # Si es POST Graba
    if request.method == 'POST':
        data = json.loads(request.body)
        nombre = data["nombre"]
        patrocinador = Patrocinador(nombre=nombre)
        patrocinador.save()
        return HttpResponse(serializers.serialize("json", [patrocinador]))
    # Si es GET Lista
    elif request.method == 'GET':
        patrocinadores = Patrocinador.objects.all()
        return HttpResponse(serializers.serialize("json", patrocinadores))
    else:
        raise NotFound(detail="No se encuentra comando rest patrocinadores con metodo " + request.method)

#Atiende las peticiones de un Patrocinador determinado
@csrf_exempt
def patrocinadores_id(request, id):

    # Si es DELETE Borra
    if request.method == 'DELETE':
        patrocinador = Patrocinador.objects.get(id=id)
        patrocinador.delete()
        return JsonResponse({"Mensaje":"Patrocinador " + id + " borrado"})
    # Si es PUT Actualiza
    elif request.method == 'PUT':
        patrocinador = Patrocinador.objects.get(id=id)
        data = json.loads(request.body)
        patrocinador.nombre = data["nombre"]
        patrocinador.save()
        return HttpResponse(serializers.serialize("json", [patrocinador]))
    # Si es GET Lista
    elif request.method == 'GET':
        patrocinador = Patrocinador.objects.get(id=id)
        return HttpResponse(serializers.serialize("json", [patrocinador]))
    else:
        raise NotFound(detail="No se encuentra comando rest patrocinadores con metodo " + request.method)


#Atiende las peticiones de los Proyectos
@csrf_exempt
def proyectos(request):

    # Si es POST Graba
    if request.method == 'POST':
        data = json.loads(request.body)
        nombre = data["nombre"]
        descripcion = data["descripcion"]
        fechaInicioUnicode = data["fechaInicio"]
        fechaInicio = None
        if fechaInicioUnicode is not None:
            fechaInicio = datetime.strptime(fechaInicioUnicode, '%Y-%m-%d')
        fechaFinalUnicode = data["fechaFinal"]
        fechaFinal = None
        if fechaFinalUnicode is not None:
            fechaFinal = datetime.strptime(fechaFinalUnicode, '%Y-%m-%d')
        prioridad = data["prioridad"]
        avance = data["avance"]
        estado = data["estado"]
        idPatrocinador = data["idPatrocinador"]
        patrocinador = Patrocinador.objects.get(id=idPatrocinador)
        if patrocinador is None:
            raise ValidationError({'idPatrocinador': ['No existe este patrocinador']})
        proyecto = Proyecto(nombre=nombre, descripcion=descripcion, fechaInicio=fechaInicio, fechaFinal=fechaFinal,
                            prioridad=prioridad, avance=avance, estado=estado, patrocinador=patrocinador)
        proyecto.save()
        return HttpResponse(serializers.serialize("json", [proyecto]))
    # Si es GET Lista
    elif request.method == 'GET':
        proyectos = Proyecto.objects.all()
        return HttpResponse(serializers.serialize("json", proyectos))
    else:
        raise NotFound(detail="No se encuentra comando rest proyectos con metodo " + request.method)

#Atiende las peticiones de un Proyecto determinado
@csrf_exempt
def proyectos_id(request, id):

    # Si es DELETE Borra
    if request.method == 'DELETE':
        proyecto = Proyecto.objects.get(id=id)
        proyecto.delete()
        return JsonResponse({"Mensaje":"Proyecto " + id + " borrado"})
    # Si es PUT Actualiza
    elif request.method == 'PUT':
        proyecto = Proyecto.objects.get(id=id)
        data = json.loads(request.body)
        proyecto.nombre = data["nombre"]

        proyecto.nombre = data["nombre"]
        proyecto.descripcion = data["descripcion"]
        fechaInicioUnicode = data["fechaInicio"]
        proyecto.fechaInicio = None
        if fechaInicioUnicode is not None:
            proyecto.fechaInicio = datetime.strptime(fechaInicioUnicode, '%Y-%m-%d')
        fechaFinalUnicode = data["fechaFinal"]
        proyecto.fechaFinal = None
        if fechaFinalUnicode is not None:
            proyecto.fechaFinal = datetime.strptime(fechaFinalUnicode, '%Y-%m-%d')
        proyecto.prioridad = data["prioridad"]
        proyecto.avance = data["avance"]
        proyecto.estado = data["estado"]
        idPatrocinador = data["idPatrocinador"]
        patrocinador = Patrocinador.objects.get(id=idPatrocinador)
        if patrocinador is None:
            raise ValidationError({'idPatrocinador': ['No existe este patrocinador']})
        proyecto.patrocinador = patrocinador
        proyecto.save()
        return HttpResponse(serializers.serialize("json", [proyecto]))
    # Si es GET Lista
    elif request.method == 'GET':
        proyecto = Proyecto.objects.get(id=id)
        return HttpResponse(serializers.serialize("json", [proyecto]))
    else:
        raise NotFound(detail="No se encuentra comando rest proyectos con metodo " + request.method)

laboratorio/views/viewsElemento.py
import json
from django.http import JsonResponse
from django.core import serializers
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.exceptions import ValidationError, NotFound
from ..models import Elemento, Paso, UnidadElemento

@csrf_exempt
def elementos(request):

    if request.method == 'POST':
        data = json.loads(request.body)
        elemento = Elemento()
        if data.has_key("id"):
            elemento.id = data["id"]
        if data.has_key("nombre"):
            elemento.nombre = data["nombre"]
        if data.has_key("cantidad"):
            elemento.cantidad = data["cantidad"]
        if data.has_key("unidades"):
            elemento.unidades = data["unidades"]
        if data.has_key("idPaso"):
            idPaso = data["idPaso"]
            try:
                paso = Paso.objects.get(id=idPaso)
            except:
                raise ValidationError({'idPaso': ['No existe paso ' + idPaso]})
            elemento.paso = paso
        elemento.save()
        return HttpResponse(serializers.serialize("json", [elemento]), content_type="application/json")

    elif request.method == 'GET':
        elementos = Elemento.objects.all()
        return HttpResponse(serializers.serialize("json", elementos), content_type="application/json")
    else:
        raise NotFound(detail="No se encuentra comando rest elementos con metodo " + request.method)


@csrf_exempt
def elementos_id(request, id):

    if request.method == 'DELETE':
        try:
            elemento = Elemento.objects.get(id=id)
        except:
            raise ValidationError({'id': ['No existe elemento ' + id]})
        elemento.delete()
        return JsonResponse({"Mensaje":"Elemento " + id + " borrado"})

    elif request.method == 'PUT':
        try:
            elemento = Elemento.objects.get(id=id)
        except:
            raise ValidationError({'id': ['No existe elemento ' + id]})
        data = json.loads(request.body)
        algoCambio = False
        if data.has_key("nombre"):
            elemento.nombre = data["nombre"]
            algoCambio = True
        if data.has_key("cantidad"):
            elemento.cantidad = data["cantidad"]
            algoCambio = True
        if data.has_key("unidades"):
            elemento.unidades = data["unidades"]
            algoCambio = True
        if data.has_key("idPaso"):
            idPaso = data["idPaso"]
            algoCambio = True
            try:
                paso = Paso.objects.get(id=idPaso)
            except:
                raise ValidationError({'idPaso': ['No existe paso ' + idPaso]})
            elemento.paso = paso
        if algoCambio:
            elemento.save()
        return HttpResponse(serializers.serialize("json", [elemento]), content_type="application/json")

    elif request.method == 'GET':
        try:
            elemento = Elemento.objects.get(id=id)
        except:
            raise ValidationError({'id': ['No existe elemento ' + id]})
        return HttpResponse(serializers.serialize("json", [elemento]), content_type="application/json")
    else:
        raise NotFound(detail="No se encuentra comando rest elementos/{id} con metodo " + request.method)


#Atiende las peticiones de Unidades de Elemento
@csrf_exempt
def lista_unidades_elemento(request):
    if request.method == 'GET':
        try:
            unidades = UnidadElemento().getDict()
            print unidades
        except:
            raise ValidationError({'id': ['No fue posible generar la lista de unidades de elemento']})
        return HttpResponse(json.dumps(unidades), content_type="application/json")
    else:
        raise NotFound(detail="No se encuentra comando rest unidadeselemento/ con metodo " + request.method)

laboratorio/views/viewsReports.py
from django.shortcuts import render


def progress(request):
    return render(request, 'laboratorio/Reporte/ReportProgressByProject.html')

def trazabilidad(request):
    return render(request, 'laboratorio/Reporte/ReporteTrazabilidad.html')

laboratorio/templates/laboratorio/Protocolo/EditProtocol.html
{% extends 'laboratorio/base.html' %}
{% load staticfiles %}
    <title>Creación de protocolo</title>
{% block header_text %}
    <link href="{% static 'css/alertify.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.rtl.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-te-1.4.0.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/alertify.js'%} "></script>
    <script src="{% static 'js/moment.js'%} "></script>
    <script src="{% static 'js/jquery-te-1.4.0.min.js'%} "></script>
    <script src="{% static 'js/Laboratory/ProtocoloController.js' %} "></script>
    <script type="application/javascript">
        $(document).ready(function () {
            $('.jqte_editor').jqte();
        });
        $("body").ready(function (){

             $.getJSON("{%url 'laboratorio:listaCategoriasProtocolo'%}").done(
                 function(response){
                    showCategorias(response);
                     var category = {{ protocol.categoria}};
                    $("#categoria option[value=" + category+"]").attr("selected","selected");
                 });
            var isEnable = "{{ protocol.habilitado }}".toLowerCase() === 'true';
            $("#habilitado").prop('checked', isEnable);
        });
    </script>

{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Crear protocolo</h1>
            <form class="form-horizontal" method="PUT" edit-protocol-url="{%url 'laboratorio:protocoloId' id=0%}"  id-protocol-data = {{ protocol.id }}  id="formProtocolo">
            {%csrf_token%}
                <div class="form-group">
                    <label for="titulo" class="col-sm-2 control-label">Titulo de Protocolo: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="text" name="titulo" id="titulo" maxlength="100" value="{{ protocol.titulo }}"  autofocus placeholder="Titulo de protocolo" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="version" class="col-sm-2 control-label">Versión: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="number" name="version" id="version" value="{{ protocol.version }}" disabled>
                    </div>
                </div>
                <div class="form-group">
                    <label for="categoria" class="col-sm-2 control-label">Categoria: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="categoria" id="categoria">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="habilitado" class="col-sm-2 control-label">Habilitado: </label>
                    <div class="col-sm-1">
                        <input class="form-control" type="checkbox" name="habilitado" id="habilitado"  placeholder="Habilitado" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="descripcion" class="col-sm-2 control-label">Descripción: </label>
                    <div class="col-sm-7">
                        <textarea class="jqte_editor" name="descripcion"   cols="100" rows="5" id="descripcion" placeholder="Descripción" >{{ protocol.descripcion }}</textarea>
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-10">
                    <input class="btn btn-warning" id="btn_guardar" type="button" onclick="updateProtocol();" value="Guardar"/>
                    <a id="link_regresar" href="{% url 'laboratorio:listarProtocolos' %}" class="btn btn-warning">Regresar</a>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

laboratorio/templates/laboratorio/Protocolo/agregarProtocolo.html
{% extends 'laboratorio/base.html' %}
{% load staticfiles %}
    <title>Creación de protocolo</title>
{% block header_text %}
    <link href="{% static 'css/alertify.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.rtl.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-te-1.4.0.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'js/alertify.js'%} "></script>
    <script src="{% static 'js/moment.js'%} "></script>
    <script src="{% static 'js/jquery-te-1.4.0.min.js'%} "></script>
    <script src="{% static 'js/Laboratory/ProtocoloController.js' %} "></script>
    <script type="application/javascript">
        $(document).ready(function () {
            $('.jqte_editor').jqte();
        });
    </script>
    <script type="application/javascript">
        $("body").ready(function (){
             $.getJSON("{%url 'laboratorio:listaCategoriasProtocolo'%}").done(showCategorias);
        });
    </script>

{% endblock %}
{% block content %}
    <section>
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Crear protocolo</h1>
            <form class="form-horizontal" method="POST" save-protocolo-url="{%url 'laboratorio:protocolos'%}" id="formProtocolo">
            {%csrf_token%}
                <div class="form-group">
                    <label for="titulo" class="col-sm-2 control-label">Titulo de Protocolo: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="text" name="titulo" id="titulo" maxlength="100" value=""  autofocus placeholder="Titulo de protocolo" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="version" class="col-sm-2 control-label">Versión: </label>
                    <div class="col-sm-6">
                        <input class="form-control" type="number" name="version" id="version" value="1" placeholder="Versión" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="categoria" class="col-sm-2 control-label">Categoria: </label>
                    <div class="col-sm-6">
                        <select class="form-control" name="categoria" id="categoria">
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="habilitado" class="col-sm-2 control-label">Habilitado: </label>
                    <div class="col-sm-1">
                        <input class="form-control" type="checkbox" name="habilitado" id="habilitado" checked  placeholder="Habilitado" required="">
                    </div>
                </div>
                <div class="form-group">
                    <label for="descripcion" class="col-sm-2 control-label">Descripción: </label>
                    <div class="col-sm-7">
                        <textarea class="jqte_editor" name="descripcion"  cols="100" rows="5" id="descripcion" placeholder="Descripción" ></textarea>
                    </div>
                </div>
                <div class="col-sm-offset-4 col-sm-10">
                    <input class="btn btn-warning" id="btn_guardar" type="button" onclick="trySaveProtocolo();" value="Guardar"/>
                    <a id="link_regresar" href="{% url 'laboratorio:listarProtocolos' %}" class="btn btn-warning">Regresar</a>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

laboratorio/templates/laboratorio/Protocolo/protocolos.html
{% extends 'laboratorio/base.html' %}
{% load staticfiles %}
{% block header_text %}
    <script
   		   src="https://code.jquery.com/jquery-3.2.1.js"
   		   integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
   		   crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.13/js/dataTables.bootstrap.min.js"></script>
    <script src="{% static 'js/Laboratory/ProtocoloController.js' %}"></script>
    <link href="{% static 'css/alertify.css' %}" rel="stylesheet">
    <link href="{% static 'css/alertify.rtl.css' %}" rel="stylesheet">
    <script>
    $(document).ready( function () {
        var urlNewVersion = "{% url 'laboratorio:protocoloIdNuevaVersion' id=0 %}";
        var urlDisable = "{% url 'laboratorio:protocoloIdDesahabilitar' id=0 %}";
        var urlFilter = "{% url 'laboratorio:ProtocoloFiltro'%}";
        var urlDetails = "{% url 'laboratorio:detallarProtocolo'  id=0%}";
        var urlEdit = "{% url 'laboratorio:editProtocol' id=0 %}";
        listarProtocolos(urlDetails,urlEdit,urlNewVersion,urlDisable,urlFilter);
    } );
    </script>
{% endblock %}
{% block content %}
    <section id="portfolio" >
        <div class="container">
            <h1 class="text-center" style="color:#fed136">Protocolos</h1>
            <a id="linkAgregarProtocolo" href="{%url 'laboratorio:agregarProtocolo'%}" class="btn btn-success btn-round img-crear"><span class="glyphicon glyphicon-plus"></span></a>
            <div class="row">
                <div class="datagrid ">
                    <table id="myTable" class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Descripción</th>
                                <th>Versión</th>
                                <th>Categoria</th>
                                <th>Habilitado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
             </div>
         </div>
    </section>
{% endblock %}